# Лабораторная работа № 6

Мацыкина А.С.

Группа: Т12О-101М-20

Дата: 24.11.2020

In [2]:
import sys
import numpy as np
import pandas as pd

### 1. Найти евклидово расстоняие между двумя объектами серии

In [3]:
s1 = pd.Series(np.random.randint(low=1, high=10, size=5))
s2 = pd.Series(np.random.randint(low=1, high=10, size=5))
print(s1)
print()
print(s2)
print()
ans = np.linalg.norm(s1-s2)
print(ans)
print()
ans2 = sum((s1-s2)**2)**0.5
print(ans2)

0    9
1    9
2    6
3    8
4    7
dtype: int32

0    4
1    6
2    1
3    2
4    9
dtype: int32

9.9498743710662

9.9498743710662


### 2. Найти индексы локальных максимумов в объекте Series

In [4]:
s = pd.Series([1, 5, 7, 22, 4])
print(s)
print()
dd = np.diff(np.sign(np.diff(s)))
print()

print(np.diff(s, n=1))
print()
print(np.sign(np.diff(s)))
print()
print(dd)
print()
print(dd==-2)
print()
print()

ans = np.where(dd == -2)[0] + 1
print(ans)

0     1
1     5
2     7
3    22
4     4
dtype: int64


[  4   2  15 -18]

[ 1  1  1 -1]

[ 0  0 -2]

[False False  True]


[3]


### 3. Заменить пробелы имяее часто встречающимися символами

In [17]:
str_test = 'brb wb ty'
s = pd.Series(list(str_test))
print(s)
print()
freq = s.value_counts()
print(freq)
print()
least_freq = freq.dropna().index[-1]
print(least_freq)
print()
''.join(s.replace(' ', least_freq))

0    b
1    r
2    b
3     
4    w
5    b
6     
7    t
8    y
dtype: object

b    3
     2
r    1
t    1
y    1
w    1
dtype: int64

w



'brbwwbwty'

### 4.  Создать объект Series, который содержит в индексах даты выходных дней субботы, а в значениях случайные числа от 1 до 10

In [33]:
#var 1
a = pd.Series(np.random.randint(low=1,high=10,size=[10]))
print(a)
print()
b = pd.Series(pd.date_range('2020-01-01', periods=10, freq='W-SAT'))
print(b)
print()
s1 = pd.concat([b, a], axis = 1)
print(s1)
print()
#var 2
s = pd.Series(np.random.randint(low=1,high=10,size=[10]), pd.date_range('2018-01-01', periods=10, freq='W-SAT'))
print(s)

0    3
1    2
2    3
3    9
4    7
5    7
6    2
7    4
8    6
9    9
dtype: int32

0   2020-01-04
1   2020-01-11
2   2020-01-18
3   2020-01-25
4   2020-02-01
5   2020-02-08
6   2020-02-15
7   2020-02-22
8   2020-02-29
9   2020-03-07
dtype: datetime64[ns]

           0  1
0 2020-01-04  3
1 2020-01-11  2
2 2020-01-18  3
3 2020-01-25  9
4 2020-02-01  7
5 2020-02-08  7
6 2020-02-15  2
7 2020-02-22  4
8 2020-02-29  6
9 2020-03-07  9

2018-01-06    7
2018-01-13    8
2018-01-20    9
2018-01-27    4
2018-02-03    6
2018-02-10    6
2018-02-17    2
2018-02-24    7
2018-03-03    1
2018-03-10    5
Freq: W-SAT, dtype: int32


### 5. Заполнить пропущенные даты, выше (заполненной даты)

In [43]:
s = pd.Series([2, 5, 8, np.nan], pd.to_datetime(['2020-01-01', '2020-01-03', '2020-01-06', '2020-01-08']))
print(s)
print()
ans = s.resample('D').ffill()
print(ans)
print()
ans1 = s.resample('D').bfill()
print(ans2)
print()

2020-01-01    2.0
2020-01-03    5.0
2020-01-06    8.0
2020-01-08    NaN
dtype: float64

2020-01-01    2.0
2020-01-02    2.0
2020-01-03    5.0
2020-01-04    5.0
2020-01-05    5.0
2020-01-06    8.0
2020-01-07    8.0
2020-01-08    NaN
Freq: D, dtype: float64

2020-01-01    2.0
2020-01-02    5.0
2020-01-03    5.0
2020-01-04    8.0
2020-01-05    8.0
2020-01-06    8.0
2020-01-07    NaN
2020-01-08    NaN
Freq: D, dtype: float64



### 6. Вычислить автокорреляцию объекта Серия

In [50]:
n = 5
s = pd.Series(np.arange(n))
print(s)
print()
a = np.random.normal(1, 3, n)
print(a)
print()
s = s + a
print(s)
print()
autocorr = [s.autocorr(lag=i).round(2) for i in range(n)]
 
print(autocorr)

0    0
1    1
2    2
3    3
4    4
dtype: int32

[ 1.31558688 -3.23079673 -0.24338835  1.84681052 -2.70893246]

0    1.315587
1   -2.230797
2    1.756612
3    4.846811
4    1.291068
dtype: float64

[1.0, -0.01, -1.0, 1.0, nan]
