# Лабораторная работа  № 1


Группа: Т12О-101М-20
Студент: Мацыкина А.С.
Дата: 17.10.2020


# Импортировать numpy под именем np

In [25]:
import numpy as np

# Напечатать версию и конфигурацию

In [80]:
print(np.__version__)
np.show_config()

1.19.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/UseR/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/UseR/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/UseR/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/UseR/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/UseR/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/UseR/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/UseR/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/UseR/anaconda3\\Library\\include']


# Создать вектор (одномерный массив) размера 10, заполненный нулями

In [84]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Создать вектор размера 10, заполненный единицами

In [29]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Создать вектор размера 10, заполненный числом 2.5

In [30]:
np.full((10,), 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

# Как получить документацию о функции numpy.add из командной строки?

In [86]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

# Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [32]:
Vec = np.zeros(10)
Vec[4] = 1
print(Vec)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Создать вектор со значениями от 10 до 49

In [33]:
Vec = np.arange(10,50)
print(Vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Развернуть вектор (первый становится последним)

In [61]:
Vec = np.arange(10)
np.flip(Vec, 0)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [62]:
Vec = np.arange(9).reshape(3,3)
print(Vec)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [46]:
Vec = np.nonzero([1,2,0,0,4,0])
print(Vec)

(array([0, 1, 4], dtype=int64),)


# Создать массив 3x3x3 со случайными значениями

In [65]:
Vec = np.random.randint((3,3,3), size=(3, 3, 3))
print(Vec)

[[[1 1 0]
  [0 1 1]
  [1 2 1]]

 [[2 0 1]
  [1 2 2]
  [1 2 1]]

 [[1 0 1]
  [0 0 2]
  [0 2 2]]]


# Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [69]:
Vec = np.random.random((10,10))
print(Vec.min(), Vec.max())

0.00413055212653779 0.9983717462265144


# Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [66]:
Vec = np.random.random(30)
s = Vec.mean()
print(s)


0.5270332418030075


# Создать матрицу с 0 внутри, и 1 на границах

In [56]:
Vec = np.ones((5, 5))
Vec[1:-1,1:-1] = 0
Vec

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Выяснить результат следующих выражений

	0 * np.nan
	np.nan == np.nan
	np.inf > np.nan
	np.nan - np.nan

In [72]:
0 * np.nan

nan

In [73]:
np.nan == np.nan

False

In [74]:
np.inf > np.nan

False

In [75]:
np.nan - np.nan

nan

# Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [76]:
Vec = np.diag(np.arange(1, 5), k=-1)
print(Vec)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# Создать 8x8 матрицу и заполнить её в шахматном порядке

In [77]:
Vec = np.zeros((8,8), dtype=int)
Vec[1::2,::2] = 1
Vec[::2,1::2] = 1
print(Vec)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [78]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


# Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [79]:
Vec = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Vec)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
