# Лабораторная работа № 2

Мацыкина А.С.

Группа: Т12О-101М-20

Дата: 30.10.2020

In [1]:
import numpy as np

## 1. Перемножить матрицы 5x3 и 3x2

In [4]:
M = np.dot(np.ones((5,3)), np.ones((3,2)))
print(M)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


## 2. Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [14]:
mass = np.arange(10)
mass[(3 < mass) & (mass <= 8)] *= -1
print(mass)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


## 3. Создать 5x5 матрицу со значениями в строках от 0 до 4

In [9]:
M = np.zeros((5,5))
M += np.arange(5)
print(M)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## 4. Есть генератор, сделать с его помощью массив

In [15]:
def generate():
    for x in range(10):
        yield x
mass = np.fromiter(generate(),dtype=float,count=-1)
print(mass)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 5. Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [16]:
Vec = np.linspace(0,1,12)[1:-1]
print(Vec)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


## 6. Отсортировать вектор

In [18]:
Vec = np.random.random(15)
Vec.sort()
print(Vec)

[0.0137635  0.13645569 0.18399993 0.22357971 0.33060814 0.39729818
 0.44570123 0.47868136 0.55545813 0.63573043 0.75819308 0.78855386
 0.78989598 0.79785044 0.81645598]


## 7. Проверить, одинаковы ли 2 numpy массива

In [29]:
mass1 = np.array([7, 5, 0])
mass2 = np.array([0, 5, 7])
equal = np.allclose(mass1, mass2)
print(equal)

False


## 8. Сделать массив неизменяемым

In [28]:
mass = np.ones(10)
mass.flags.writeable = False
mass[0] = 5

ValueError: assignment destination is read-only

## 9. Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [31]:
mass = np.random.random((10,2))
X,Y = mass[:,0], mass[:,1]
R = np.hypot(X, Y)
T = np.arctan2(Y, X)
print(R)
print(T)

[0.5175356  0.79139955 0.50299621 1.16232888 1.02593825 0.73662589
 1.01026126 0.85354658 1.0082513  0.79372895]
[0.19211882 0.63582914 0.98045373 0.82315637 0.47878392 0.58701004
 1.2823441  0.73478755 0.25467204 0.05653824]


## 10. Заменить максимальный элемент на ноль

In [32]:
mass = np.random.random(10)
mass[mass.argmax()] = 0
print(mass)

[0.30477047 0.51192265 0.27638571 0.         0.30859986 0.29096637
 0.28321258 0.03671995 0.10292091 0.10905602]


## 11. Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [37]:
mass = np.zeros((5,5), [('x',float),('y',float)])
mass['x'], mass['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(mass)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


## 12. Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [51]:
mass1 = np.random.random(5)
mass2 = np.random.random(5)
M = 1 / (mass1.reshape((-1, 1)) - mass2)
print(M)

[[ -1.43264167 -11.0310757   -2.02056431  -1.18027311 -28.44168615]
 [  3.50594489   1.12033763   2.04779633   7.35404809   1.05476175]
 [ 26.9848451    1.5517924    4.16392821  -8.91325618   1.4287563 ]
 [  3.62854563   1.13256598   2.08902369   7.91500997   1.06559357]
 [  5.08053345   1.24349036   2.50043929  21.01748031   1.16322175]]


## 13. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [53]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.uint8, np.uint16, np.uint32, np.uint64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float16, np.float32, np.float_]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
for dtype in [np.complex64, np.complex128]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)

-128
127
-32768
32767
-2147483648
2147483647
-9223372036854775808
9223372036854775807
0
255
0
65535
0
4294967295
0
18446744073709551615
-65500.0
65500.0
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


## 14. Напечатать все значения в массиве

In [58]:
mass = np.random.random(5)
print(mass)
print()
for i in mass:
    print(i)

[0.18837256 0.14383601 0.14695199 0.70290127 0.67656914]

0.18837256370339772
0.14383600839119448
0.1469519934475877
0.7029012714755197
0.6765691351252319


## 15. Найти ближайшее к заданному значению число в заданном массиве

In [66]:
mass1 = np.arange(10)
mass2 = np.random.randint(10)
index = (np.abs(mass1-mass2)).argmin()
print(mass1, mass2)
print(mass1[index])

[0 1 2 3 4 5 6 7 8 9] 6
6


## 16. Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [68]:
Z = np.zeros(10, [ ('position', [('x', float, 1),
                                 ('y', float, 1)]),
                  ('color',    [('r', float, 1),
                                ('g', float, 1),
                                ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-68-c2f96bc0deb6>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [('x', float, 1),


## 17. Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [113]:
import scipy.spatial

mass = np.random.random((100,2))
len_ = scipy.spatial.distance.cdist(mass,mass)
print(len_)

[[0.         0.60122771 0.35712995 ... 0.57380832 0.49438523 0.07521884]
 [0.60122771 0.         0.95464174 ... 0.18792431 1.03809822 0.58746919]
 [0.35712995 0.95464174 0.         ... 0.92891372 0.36784091 0.3696166 ]
 ...
 [0.57380832 0.18792431 0.92891372 ... 0.         0.9452316  0.58405924]
 [0.49438523 1.03809822 0.36784091 ... 0.9452316  0.         0.5552779 ]
 [0.07521884 0.58746919 0.3696166  ... 0.58405924 0.5552779  0.        ]]


## 18. Преобразовать массив из float в int

In [74]:
mass = np.arange(10, dtype=np.float32)
mass = mass.astype(np.int32, copy=False)
print(mass)

[0 1 2 3 4 5 6 7 8 9]


## 19. Дан файл:

1,2,3,4,5

6,,,7,8

,,9,10,11

#### Как прочитать его?

In [148]:
with open('./test_file.txt', 'w') as f:
    f.write('1,2,3,4,5\n6,,,7,8\n,,9,10,11')

np.genfromtxt('./test_file.txt', delimiter = ',')

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

## 20. Каков эквивалент функции enumerate для numpy массивов?

In [105]:
mass = np.array([[5, 0], [7, 0]])
for index in np.ndindex(mass.shape):
    print(index, mass[index])

(0, 0) 5
(0, 1) 0
(1, 0) 7
(1, 1) 0


## 21. Сформировать 2D массив с распределением Гаусса

In [108]:
mass = np.random.normal(size = (5,5))
print(mass)

[[ 9.30313842e-01  1.06743954e+00 -1.31018218e+00  3.34411727e-01
   1.08140450e-01]
 [-1.07875088e+00  6.72476670e-01  6.03380655e-01  1.57832705e+00
   9.73838572e-01]
 [ 8.83218821e-01 -6.01283236e-01 -9.53810075e-01  5.07657472e-02
   1.16996428e+00]
 [-3.87938245e-01  1.39840713e+00  1.37007838e+00  3.03882249e-01
  -7.29223294e-04]
 [ 3.13165295e-01 -2.10681914e-01  1.14868751e+00 -1.24951969e-01
   2.91453802e-01]]


## 22. Случайно расположить p элементов в 2D массив

In [111]:
n = 5
p = 12
mass = np.zeros((n,n))
np.put(mass, np.random.choice(range(n*n), p, replace=False), 1)
print(mass)

[[1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1.]
 [0. 1. 0. 1. 1.]]


## 23. Отнять среднее из каждой строки в матрице 

In [120]:
M = np.random.rand(5, 5)
print(M)
print()
M1 = M - M.mean(axis=1, keepdims=True)
print(M1)

[[0.32163741 0.05779863 0.84452781 0.55870429 0.75447887]
 [0.14020686 0.06886714 0.06071711 0.30030226 0.3134883 ]
 [0.25221213 0.49846799 0.47364455 0.71181609 0.37931371]
 [0.52567492 0.24253674 0.43456391 0.23488487 0.92042347]
 [0.60208434 0.64200578 0.80711066 0.84265512 0.52333129]]

[[-0.18579199 -0.44963078  0.33709841  0.05127489  0.24704947]
 [-0.03650948 -0.1078492  -0.11599922  0.12358593  0.13677196]
 [-0.21087876  0.03537709  0.01055366  0.24872519 -0.08377718]
 [ 0.05405814 -0.22908004 -0.03705287 -0.23673191  0.44880669]
 [-0.0813531  -0.04143166  0.12367322  0.15921768 -0.16010615]]


## 24. Отсортировать матрицу по n-ому столбцу

In [124]:
M = np.random.randint(0,5,(4,8))
n = 3
print(M)
print()
print(M[M[:,n].argsort()])

[[2 2 4 0 2 0 2 1]
 [2 1 1 4 4 3 3 4]
 [1 0 4 3 4 2 1 1]
 [2 4 4 0 0 4 1 1]]

[[2 2 4 0 2 0 2 1]
 [2 4 4 0 0 4 1 1]
 [1 0 4 3 4 2 1 1]
 [2 1 1 4 4 3 3 4]]


## 25. Определить, есть ли в 2D массиве нулевые столбцы

In [127]:
mass = np.random.randint(0,6,(2,8))
print((~mass.any(axis=0)).any())

False



## 26. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [149]:
mass = np.ones(5)
mass1 = np.random.randint(0,len(mass),15)
mass += np.bincount(mass1, minlength=len(mass))
print(mass)

[4. 2. 2. 3. 9.]


## 27. Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [153]:
w, h = 24, 24
pixel_colors = np.random.randint(0, 2, (h, w, 3)).astype(np.ubyte)
pixel_colors_as_vector = pixel_colors.reshape((h*w, 3))
uniq_colors = np.unique(pixel_colors_as_vector, axis=0)
len(uniq_colors)

8

## 28. Дан четырехмерный массив, посчитать сумму по последним двум осям

In [141]:
mass = np.random.randint(0,5, (2,4,2,4))
sum = mass.reshape(mass.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[21 21  9 17]
 [16 23 14 22]]


## 29. Найти диагональные элементы произведения матриц

In [147]:
M = np.array([[5,5], [7,0]])
print(M)
M1 = np.array([[5,4], [7,4]])
print(M1)
print()
print(np.dot(M, M1))
print()
print(np.diag(np.dot(M, M1)))

[[5 5]
 [7 0]]
[[5 4]
 [7 4]]

[[60 40]
 [35 28]]

[60 28]
