# Лабораторная работа № 2

Мацыкина А.С.

Группа: Т12О-101М-20

Дата: 30.10.2020

In [4]:
import numpy as np

## 1. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [6]:
Vec = np.array([1,2,3,4,5])
n = 3
Vec1 = np.zeros(len(Vec) + (len(Vec)-1)*(n))
Vec1[::n + 1] = Vec
print(Vec1)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


## 2. Поменять 2 строки в матрице

In [15]:
M = np.arange(9).reshape(3,3)
print(M)
print()
M[[0,1]] = M[[1,0]]
print(M)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[3 4 5]
 [0 1 2]
 [6 7 8]]


## 3. Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

In [16]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 17) ( 0, 89) ( 5, 36) ( 5, 40) ( 7, 42) ( 7, 84) ( 9, 58) ( 9, 72)
 (11, 19) (11, 40) (15, 24) (15, 39) (17, 51) (17, 65) (17, 89) (19, 40)
 (24, 39) (29, 40) (29, 95) (36, 40) (40, 95) (42, 84) (45, 83) (45, 98)
 (46, 47) (46, 67) (47, 67) (51, 65) (58, 72) (83, 98)]


## 4. Дан массив C; создать массив A, что np.bincount(A) == C

In [17]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


## 5. Посчитать среднее, используя плавающее окно

In [18]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(moving_average(np.arange(20), 3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


## 6. Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

In [19]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


## 7. Инвертировать булево значение, или поменять знак у числового массива без создания нового

In [29]:
Z = np.random.randint(0,2,100)
print(Z)
print()
np.logical_not(Z, out = Z)

[0 0 1 1 0 0 1 1 0 0 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0
 1 1 1 0 1 1 0 1 0 1 0 0 1 1 0 0 0 1 0 1 0 1 0 0 1 1 0 0 1 1 1 0 0 1 0 1 1
 0 1 1 1 0 0 1 1 0 0 0 0 1 0 1 0 0 1 1 1 1 1 0 1 0 0]



array([1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1])

In [30]:
Z = np.random.uniform(-1.0,1.0,100)
print(Z)
print()
np.negative(Z, out=Z)

[ 1.13470301e-01 -2.04501739e-01  9.15723190e-01  7.22813856e-01
  8.06076358e-01  8.08277033e-02  7.61325688e-01  8.33455332e-01
  6.62185146e-01 -3.05006903e-01 -9.95459095e-01  8.01215724e-01
  5.15634428e-03  7.37301548e-01 -1.91900188e-03 -2.40290949e-01
 -9.79518649e-01 -8.22536908e-01 -1.75617208e-01  3.53753811e-01
 -8.22046308e-01 -6.72526783e-01 -5.03029608e-01  4.55814062e-01
  6.28807447e-01 -1.45378086e-01  4.46842569e-01  3.35367659e-01
  7.60116573e-01  2.20854114e-01  3.89085162e-01  2.72841288e-01
 -2.56361998e-01  1.01107233e-01 -6.15812824e-01 -8.72425165e-01
  4.86000228e-01 -9.57309238e-01  9.56955495e-01  9.82158620e-01
 -4.87954661e-01  4.77984810e-01 -2.19495469e-01 -8.47156327e-01
 -1.39042740e-01  4.73534148e-01  2.39578797e-02  3.41418580e-01
  7.09795305e-01 -1.08891372e-01 -9.70064100e-01 -1.99297598e-01
 -5.88547219e-01  3.63361554e-01 -6.27803062e-01 -1.16156537e-01
  3.31176788e-01  9.05672549e-01 -2.11193468e-02  5.52891288e-01
 -5.76941923e-01  5.01745

array([-1.13470301e-01,  2.04501739e-01, -9.15723190e-01, -7.22813856e-01,
       -8.06076358e-01, -8.08277033e-02, -7.61325688e-01, -8.33455332e-01,
       -6.62185146e-01,  3.05006903e-01,  9.95459095e-01, -8.01215724e-01,
       -5.15634428e-03, -7.37301548e-01,  1.91900188e-03,  2.40290949e-01,
        9.79518649e-01,  8.22536908e-01,  1.75617208e-01, -3.53753811e-01,
        8.22046308e-01,  6.72526783e-01,  5.03029608e-01, -4.55814062e-01,
       -6.28807447e-01,  1.45378086e-01, -4.46842569e-01, -3.35367659e-01,
       -7.60116573e-01, -2.20854114e-01, -3.89085162e-01, -2.72841288e-01,
        2.56361998e-01, -1.01107233e-01,  6.15812824e-01,  8.72425165e-01,
       -4.86000228e-01,  9.57309238e-01, -9.56955495e-01, -9.82158620e-01,
        4.87954661e-01, -4.77984810e-01,  2.19495469e-01,  8.47156327e-01,
        1.39042740e-01, -4.73534148e-01, -2.39578797e-02, -3.41418580e-01,
       -7.09795305e-01,  1.08891372e-01,  9.70064100e-01,  1.99297598e-01,
        5.88547219e-01, -

## 8. Посчитать ранг матрицы

In [52]:
M = np.random.randint(0,1,(5,5))
print(M)
rang = np.linalg.matrix_rank(M)
print(rang)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0


## 9. Найти наиболее частое значение в массиве

In [53]:
mass = np.random.randint(0,5,20)
print(np.bincount(mass).argmax())

4


## 10. Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [54]:
M = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (M.shape[0] - n)
j = 1 + (M.shape[1] - n)
C = stride_tricks.as_strided(M, shape=(i, j, n, n), strides=M.strides + M.strides)
print(C)

[[[[3 3 2]
   [3 0 0]
   [2 2 3]]

  [[3 2 2]
   [0 0 0]
   [2 3 4]]

  [[2 2 4]
   [0 0 1]
   [3 4 0]]

  [[2 4 3]
   [0 1 2]
   [4 0 3]]

  [[4 3 0]
   [1 2 1]
   [0 3 3]]

  [[3 0 2]
   [2 1 3]
   [3 3 3]]

  [[0 2 0]
   [1 3 4]
   [3 3 4]]

  [[2 0 3]
   [3 4 3]
   [3 4 3]]]


 [[[3 0 0]
   [2 2 3]
   [1 0 2]]

  [[0 0 0]
   [2 3 4]
   [0 2 2]]

  [[0 0 1]
   [3 4 0]
   [2 2 1]]

  [[0 1 2]
   [4 0 3]
   [2 1 1]]

  [[1 2 1]
   [0 3 3]
   [1 1 2]]

  [[2 1 3]
   [3 3 3]
   [1 2 4]]

  [[1 3 4]
   [3 3 4]
   [2 4 3]]

  [[3 4 3]
   [3 4 3]
   [4 3 2]]]


 [[[2 2 3]
   [1 0 2]
   [4 4 3]]

  [[2 3 4]
   [0 2 2]
   [4 3 0]]

  [[3 4 0]
   [2 2 1]
   [3 0 1]]

  [[4 0 3]
   [2 1 1]
   [0 1 1]]

  [[0 3 3]
   [1 1 2]
   [1 1 0]]

  [[3 3 3]
   [1 2 4]
   [1 0 3]]

  [[3 3 4]
   [2 4 3]
   [0 3 0]]

  [[3 4 3]
   [4 3 2]
   [3 0 2]]]


 [[[1 0 2]
   [4 4 3]
   [1 1 1]]

  [[0 2 2]
   [4 3 0]
   [1 1 4]]

  [[2 2 1]
   [3 0 1]
   [1 4 3]]

  [[2 1 1]
   [0 1 1]
   [4 3 4]]

  [[1 1 2]
   

## 11. Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [55]:
p, n = 5, 10
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]]


## 12. Дан массив 16x16, посчитать сумму по блокам 4x4

In [59]:
mass = np.ones((16,16))
n = 4
Summ = np.add.reduceat(np.add.reduceat(mass, np.arange(0, mass.shape[0], n), axis=0),
                                       np.arange(0, mass.shape[1], n), axis=1)
print(Summ)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


## 13. Найти n наибольших значений в массиве

In [64]:
n = 5
mass = np.random.randint(low=1, high=10, size=[5,5])
print(mass)
print()
print(np.unique((np.sort(mass.flat)))[::-1][:n])

[[2 2 2 9 5]
 [8 1 9 4 8]
 [9 2 5 7 9]
 [4 6 2 7 7]
 [1 1 2 5 6]]

[9 8 7 6 5]


## 14. Построить прямое произведение массивов (все комбинации с каждым элементом)

In [66]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5, 6], [7, 8, 9])))

[[1 4 7]
 [1 4 8]
 [1 4 9]
 [1 5 7]
 [1 5 8]
 [1 5 9]
 [1 6 7]
 [1 6 8]
 [1 6 9]
 [2 4 7]
 [2 4 8]
 [2 4 9]
 [2 5 7]
 [2 5 8]
 [2 5 9]
 [2 6 7]
 [2 6 8]
 [2 6 9]
 [3 4 7]
 [3 4 8]
 [3 4 9]
 [3 5 7]
 [3 5 8]
 [3 5 9]
 [3 6 7]
 [3 6 8]
 [3 6 9]]


## 15. Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [67]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 3 5 6]


## 16. Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

In [69]:
M = np.random.randint(0,5,(10,3))
a = np.logical_and.reduce(M[:,1:] == M[:,:-1], axis=1)
b = M[~a]
print(M)
print()
print(b)

[[1 4 0]
 [1 4 0]
 [2 4 2]
 [0 0 2]
 [4 3 2]
 [2 4 0]
 [1 0 2]
 [4 3 0]
 [0 3 2]
 [3 3 0]]

[[1 4 0]
 [1 4 0]
 [2 4 2]
 [0 0 2]
 [4 3 2]
 [2 4 0]
 [1 0 2]
 [4 3 0]
 [0 3 2]
 [3 3 0]]


## 17. Преобразовать вектор чисел в матрицу бинарных представлений

In [70]:
Vec = np.array([0, 1, 2, 3, 4, 5, 50, 87, 170], dtype=np.uint8)
print(np.unpackbits(Vec[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0 1]
 [0 0 1 1 0 0 1 0]
 [0 1 0 1 0 1 1 1]
 [1 0 1 0 1 0 1 0]]


## 18. Дан двумерный массив. Найти все различные строки

In [73]:
mass = np.random.randint(0, 2, (10,10))
T = np.ascontiguousarray(mass).view(np.dtype((np.void, mass.dtype.itemsize * mass.shape[1])))
_, idx = np.unique(T, return_index=True)
a = mass[idx]
print(a)


[[0 0 0 1 1 1 1 0 0 0]
 [0 0 1 1 1 1 1 1 0 1]
 [0 1 0 0 0 1 0 0 0 0]
 [0 1 0 1 1 0 1 1 1 0]
 [1 0 0 1 1 0 1 1 1 0]
 [1 0 1 1 0 0 0 1 1 0]
 [1 1 0 0 1 1 1 0 0 1]
 [1 1 0 1 0 1 0 0 1 0]
 [1 1 0 1 1 0 1 1 1 1]
 [1 1 1 0 0 1 1 1 0 0]]


## 19. Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul

In [80]:
A = np.random.random((5,))
B = np.random.random((5,))
print(A)
print()
print(B)

[0.31357049 0.84044583 0.52449541 0.86890493 0.41908243]

[0.84687307 0.11949741 0.71795385 0.44847746 0.29800874]


In [82]:
np.einsum('i,i', A, B)

1.2571234923159424

In [83]:
np.einsum('i,j', A, B)

array([[0.2655544 , 0.03747086, 0.22512914, 0.14062929, 0.09344674],
       [0.71175093, 0.1004311 , 0.60340132, 0.37692101, 0.2504602 ],
       [0.44418103, 0.06267584, 0.3765635 , 0.23522437, 0.15630421],
       [0.73585218, 0.10383189, 0.62383364, 0.38968428, 0.25894126],
       [0.35490963, 0.05007926, 0.30088185, 0.18794903, 0.12489023]])

In [84]:
np.einsum('i->', A)

2.9664990815923886

In [86]:
np.einsum('i,i->i', A, B)

array([0.2655544 , 0.1004311 , 0.3765635 , 0.38968428, 0.12489023])